export const BANK_FIND_REQUEST = "BANK_FIND_REQUEST";
export const BANK_FIND_SUCCESS = "BANK_FIND_SUCCESS";
export const BANK_FIND_FAIL = "BANK_FIND_FAIL";

export const BANK_CLEAR_SEARCH = "BANK_CLEAR_SEARCH";

export const BANK_REMOVE_REQUEST = "BANK_REMOVE_REQUEST";
export const BANK_REMOVE_SUCCESS = "BANK_REMOVE_SUCCESS";
export const BANK_REMOVE_FAIL = "BANK_REMOVE_FAIL";
