export const PAYMENT_TOPUP_BANK_REQUEST = "PAYMENT_TOPUP_BANK_REQUEST";
export const PAYMENT_TOPUP_BANK_SUCCESS = "PAYMENT_TOPUP_BANK_SUCCESS";
export const PAYMENT_TOPUP_BANK_FAIL = "PAYMENT_TOPUP_BANK_FAIL";

export const PAYMENT_TOPUP_BANK_CLEAR = "PAYMENT_TOPUP_BANK_CLEAR";

export const PAYMENT_ORDER_WALLET_REQUEST = "PAYMENT_ORDER_WALLET_REQUEST";
export const PAYMENT_ORDER_WALLET_SUCCESS = "PAYMENT_ORDER_WALLET_SUCCESS";
export const PAYMENT_ORDER_WALLET_FAIL = "PAYMENT_ORDER_WALLET_FAIL";

export const PAYMENT_FIND_ONE_REQUEST = "PAYMENT_FIND_ONE_REQUEST";
export const PAYMENT_FIND_ONE_SUCCESS = "PAYMENT_FIND_ONE_SUCCESS";
export const PAYMENT_FIND_ONE_FAIL = "PAYMENT_FIND_ONE_FAIL";

export const PAYMENT_FIND_ONE_CLEAR = "PAYMENT_FIND_ONE_CLEAR";

export const PAYMENT_TRANSFER_DATA = "PAYMENT_TRANSFER_DATA";
export const PAYMENT_TRANSFER_DATA_CLEAR = "PAYMENT_TRANSFER_DATA_CLEAR";

export const PAYMENT_TRANSFER_WALLET_REQUEST =
  "PAYMENT_TRANSFER_WALLET_REQUEST";
export const PAYMENT_TRANSFER_WALLET_SUCCESS =
  "PAYMENT_TRANSFER_WALLET_SUCCESS";
export const PAYMENT_TRANSFER_WALLET_FAIL = "PAYMENT_TRANSFER_WALLET_FAIL";
export const PAYMENT_TRANSFER_WALLET_CLEAR = "PAYMENT_TRANSFER_WALLET_CLEAR";

export const PAYMENT_TRANSFER_WALLET_BANK_REQUEST =
  "PAYMENT_TRANSFER_WALLET_BANK_REQUEST";
export const PAYMENT_TRANSFER_WALLET_BANK_SUCCESS =
  "PAYMENT_TRANSFER_WALLET_BANK_SUCCESS";
export const PAYMENT_TRANSFER_WALLET_BANK_FAIL =
  "PAYMENT_TRANSFER_WALLET_BANK_FAIL";

export const PAYMENT_TRANSFER_BANK_REQUEST = "PAYMENT_TRANSFER_BANK_REQUEST";
export const PAYMENT_TRANSFER_BANK_SUCCESS = "PAYMENT_TRANSFER_BANK_SUCCESS";
export const PAYMENT_TRANSFER_BANK_FAIL = "PAYMENT_TRANSFER_BANK_FAIL";

export const PAYMENT_REQUEST_WALLET_REQUEST = "PAYMENT_REQUEST_WALLET_REQUEST";
export const PAYMENT_REQUEST_WALLET_SUCCESS = "PAYMENT_REQUEST_WALLET_SUCCESS";
export const PAYMENT_REQUEST_WALLET_FAIL = "PAYMENT_REQUEST_WALLET_FAIL";
export const PAYMENT_REQUEST_WALLET_CLEAR = "PAYMENT_REQUEST_WALLET_CLEAR";
