export const PAYMENT_TOPUP_BANK_REQUEST = "PAYMENT_TOPUP_BANK_REQUEST";
export const PAYMENT_TOPUP_BANK_SUCCESS = "PAYMENT_TOPUP_BANK_SUCCESS";
export const PAYMENT_TOPUP_BANK_FAIL = "PAYMENT_TOPUP_BANK_FAIL";

export const PAYMENT_TOPUP_BANK_CLEAR = "PAYMENT_TOPUP_BANK_CLEAR";
