export const PAYMENT_TOPUP_BANK_REQUEST = "PAYMENT_TOPUP_BANK_REQUEST";
export const PAYMENT_TOPUP_BANK_SUCCESS = "PAYMENT_TOPUP_BANK_SUCCESS";
export const PAYMENT_TOPUP_BANK_FAIL = "PAYMENT_TOPUP_BANK_FAIL";

export const PAYMENT_TOPUP_BANK_CLEAR = "PAYMENT_TOPUP_BANK_CLEAR";

export const PAYMENT_ORDER_WALLET_REQUEST = "PAYMENT_ORDER_WALLET_REQUEST";
export const PAYMENT_ORDER_WALLET_SUCCESS = "PAYMENT_ORDER_WALLET_SUCCESS";
export const PAYMENT_ORDER_WALLET_FAIL = "PAYMENT_ORDER_WALLET_FAIL";
