export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_REGISTER_REQUEST_1 = "USER_REGISTER_REQUEST_1";
export const USER_REGISTER_SUCCESS_1 = "USER_REGISTER_SUCCESS_1";
export const USER_REGISTER_FAIL_1 = "USER_REGISTER_FAIL_1";

export const USER_REGISTER_REQUEST_2 = "USER_REGISTER_REQUEST_2";
export const USER_REGISTER_SUCCESS_2 = "USER_REGISTER_SUCCESS_2";
export const USER_REGISTER_FAIL_2 = "USER_REGISTER_FAIL_2";

export const USER_FIND_ONE_REQUEST = "USER_FIND_ONE_REQUEST";
export const USER_FIND_ONE_SUCCESS = "USER_FIND_ONE_SUCCESS";
export const USER_FIND_ONE_FAIL = "USER_FIND_ONE_FAIL";

export const USER_FIND_ONE_EMAIL_REQUEST = "USER_FIND_ONE_EMAIL_REQUEST";
export const USER_FIND_ONE_EMAIL_SUCCESS = "USER_FIND_ONE_EMAIL_SUCCESS";
export const USER_FIND_ONE_EMAIL_FAIL = "USER_FIND_ONE_EMAIL_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_UPDATE_PIN_REQUEST = "USER_UPDATE_PIN_REQUEST";
export const USER_UPDATE_PIN_SUCCESS = "USER_UPDATE_PIN_SUCCESS";
export const USER_UPDATE_PIN_FAIL = "USER_UPDATE_PIN_FAIL";

export const USER_ADD_ADDRESS_REQUEST = "USER_ADD_ADDRESS_REQUEST";
export const USER_ADD_ADDRESS_SUCCESS = "USER_ADD_ADDRESS_SUCCESS";
export const USER_ADD_ADDRESS_FAIL = "USER_ADD_ADDRESS_FAIL";

export const USER_DELETE_ADDRESS_REQUEST = "USER_DELETE_ADDRESS_REQUEST";
export const USER_DELETE_ADDRESS_SUCCESS = "USER_DELETE_ADDRESS_SUCCESS";
export const USER_DELETE_ADDRESS_FAIL = "USER_DELETE_ADDRESS_FAIL";

export const USER_CLOSE_ACCOUNT_REQUEST = "USER_CLOSE_ACCOUNT_REQUEST";
export const USER_CLOSE_ACCOUNT_SUCCESS = "USER_CLOSE_ACCOUNT_SUCCESS";
export const USER_CLOSE_ACCOUNT_FAIL = "USER_CLOSE_ACCOUNT_FAIL";

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";
