export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_REGISTER_REQUEST_1 = "USER_REGISTER_REQUEST_1";
export const USER_REGISTER_SUCCESS_1 = "USER_REGISTER_SUCCESS_1";
export const USER_REGISTER_FAIL_1 = "USER_REGISTER_FAIL_1";

export const USER_REGISTER_REQUEST_2 = "USER_REGISTER_REQUEST_2";
export const USER_REGISTER_SUCCESS_2 = "USER_REGISTER_SUCCESS_2";
export const USER_REGISTER_FAIL_2 = "USER_REGISTER_FAIL_2";

export const USER_FIND_ONE_REQUEST = "USER_FIND_ONE_REQUEST";
export const USER_FIND_ONE_SUCCESS = "USER_FIND_ONE_SUCCESS";
export const USER_FIND_ONE_FAIL = "USER_FIND_ONE_FAIL";
